---
- name: import system_specific variables
  include_vars:
    "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: repo install
  import_tasks: repo-install.yml
  when: netatalk_install_from_repo|bool

# TODO - name: sources install

- name: afp.conf configuration
  template:
    src: afp.conf.j2
    dest: '{{ afp_conf_path }}'
    owner: root
    group: root
    mode: 0644
  notify: restart netatalk service

- name: Start and enable netatalk service
  service:
    name: netatalk
    enabled: true
    state: started
